targets:
  $default:
    sources:
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: 'assets/swaggers/'
          output_folder: 'lib/src/data/repositories/api/'