name: ui_kit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0

flutter:
  assets:
   - assets/media/icon_svg/sender.svg
   - assets/media/icon_svg/sender_custom.svg
